SalesOrder/Models/MasterData/CategoryClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesOrder.Models.MasterData
{

    public class CategoryListClass
    {
        public List<CategoryClass> categories { get; set; }
    }

    public class CategoryClass
    {
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
        public int totalItem { get; set; }
        public string isActive { get; set; }
    }

    public class AddCategoryClass
    {
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
    }

    public class DetailsCategoryClass
    {
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
        public string isActive { get; set; }
        public int totalItem { get; set; }
        public List<ItemClass> items { get; set; }
    }

}

SalesOrder/Models/MasterData/CustomerClass.cs
using SalesOrder.Models.Transaction;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesOrder.Models.MasterData
{

    public class CustomerListClass
    {
        public List<CustomerClass> customers { get; set; }
    }

    public class AddCustomerClass
    {
        public string customerName { get; set; }
        public string customerPhone { get; set; }
        public string customerEmail { get; set; }
        public string contactPerson { get; set; }
        public string customerCity { get; set; }
        public double creditLimit { get; set; }
    }

    public class DetailsCustomerClass
    {
        public string customerCode { get; set; }
        public string customerName { get; set; }
        public string customerPhone { get; set; }
        public string customerEmail { get; set; }
        public string contactPerson { get; set; }
        public double creditLimit { get; set; }
        public string strCreditLimit { get; set; }
        public string customerCity { get; set; }
        public string isActive { get; set; }
        public List<SalesOrderClass> soes { get; set; }
    }

    public class CustomerClass
    {
        public string customerCode { get; set; }
        public string customerName { get; set; }
        public string customerPhone { get; set; }
        public string customerEmail { get; set; }
        public string contactPerson { get; set; }
        public string customerCity { get; set; }
        public double creditLimit { get; set; }
        public string strCreditLimit { get; set; }
        public double lastCreditLimit { get; set; }
        public string strLastCreditLimit { get; set; }
        public string isActive { get; set; }
    }
}

SalesOrder/Models/MasterData/ItemClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesOrder.Models.MasterData
{
    public class ItemListClass
    {
        public List<ItemClass> items { get; set; }
    }

    public class AddItemClass
    {
        public List<CategoryClass> categories { get; set; }
        public string itemName { get; set; }
        public double itemPrice { get; set; }
        public int itemStock { get; set; }
        public string categoryCode { get; set; }
    }

    public class DetailsItemClass
    {
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public double itemPrice { get; set; }
        public string itemPriceStr { get; set; }
        public int itemStock { get; set; }
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
        public string isActive { get; set; }
        public List<CategoryClass> categories { get; set; }
    }

    public class ItemClass
    {
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public double itemPrice { get; set; }
        public string itemPriceStr { get; set; }
        public int itemStock { get; set; }
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
        public string isActive { get; set; }
    }
}

SalesOrder/Models/MasterData/UserClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesOrder.Models.MasterData
{
    public class UserListClass
    {
        public List<UserClass> users { get; set; }
    }

    public class AddUserClass
    {
        public string userName { get; set; }
        public string userRole { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userAddress { get; set; }
        public string userCity { get; set; }
    }

    public class DetailsUserClass
    {
        public string userCode { get; set; }
        public string userName { get; set; }
        public string userRole { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userAddress { get; set; }
        public string userCity { get; set; }
        public string isActive { get; set; }
    }

    public class UserClass
    {
        public string userCode { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userRole { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userAddress { get; set; }
        public string userCity { get; set; }
        public string isActive { get; set; }
    }
}

SalesOrder/Controllers/MasterDataController.cs
using EnDecDll;
using MySql.Data.MySqlClient;
using SalesOrder.Models.MasterData;
using SalesOrder.Models.Transaction;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace SalesOrder.Controllers
{
    public class MasterDataController : Controller
    {

        string constr = ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;

        public ActionResult ItemList()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ItemListClass itemListClass = new ItemListClass();
            itemListClass.items = new List<ItemClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.ItemId, a.ItemCode, a.ItemName, a.ItemPrice, a.ItemStock, b.CategoryCode, b.CategoryName, a.IsActive " +
                               "FROM m_item a " +
                               "JOIN m_category b ON b.CategoryCode = a.CategoryCode ";
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            itemListClass.items.Add(new ItemClass
                            {
                                itemCode = sdr["ItemCode"].ToString(),
                                itemName = sdr["ItemName"].ToString(),
                                itemPrice = Convert.ToDouble(sdr["ItemPrice"].ToString()),
                                itemStock = Convert.ToInt32(sdr["ItemStock"].ToString()),
                                categoryCode = sdr["CategoryCode"].ToString(),
                                categoryName = sdr["CategoryName"].ToString(),
                                isActive = sdr["IsActive"].ToString() == "True" ? "Active" : "Inactive"
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(itemListClass);
        }

        public ActionResult CategoryList()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            CategoryListClass categoryListClass = new CategoryListClass();
            categoryListClass.categories = new List<CategoryClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.CategoryCode, a.CategoryName, a.IsActive, (SELECT COUNT(*) FROM m_item b WHERE b.CategoryCode = a.CategoryCode) AS total " +
                               "FROM m_category a ";
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            categoryListClass.categories.Add(new CategoryClass
                            {
                                categoryCode = sdr["CategoryCode"].ToString(),
                                categoryName = sdr["CategoryName"].ToString(),
                                totalItem = Convert.ToInt32(sdr["total"].ToString()),
                                isActive = sdr["IsActive"].ToString() == "True" ? "Active" : "Inactive"
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(categoryListClass);
        }

        public ActionResult CustomerList()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            CustomerListClass customerListClass = new CustomerListClass();
            customerListClass.customers = new List<CustomerClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.CustomerId, a.CustomerCode, a.CustomerName, a.CustomerPhone, a.CustomerEmail, a.ContactPerson, a.CreditLimit, a.IsActive " +
                               "FROM m_customer a ";
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            customerListClass.customers.Add(new CustomerClass
                            {
                                customerCode = sdr["CustomerCode"].ToString(),
                                customerName = sdr["CustomerName"].ToString(),
                                customerPhone = sdr["CustomerPhone"].ToString(),
                                customerEmail = sdr["CustomerEmail"].ToString(),
                                contactPerson = sdr["ContactPerson"].ToString(),
                                creditLimit = Convert.ToDouble(sdr["CreditLimit"].ToString()),
                                isActive = sdr["IsActive"].ToString() == "True" ? "Active" : "Inactive"
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(customerListClass);
        }

        public ActionResult UserList()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            UserListClass userListClass = new UserListClass();
            userListClass.users = new List<UserClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.UserId, a.UserCode, a.UserName, a.UserRole, a.UserPhone, a.UserEmail, a.UserAddress, a.UserCity, a.IsActive " +
                               "FROM m_user a " + 
                               "WHERE a.UserRole != 'SA'";
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            userListClass.users.Add(new UserClass
                            {
                                userCode = sdr["UserCode"].ToString(),
                                userName = sdr["UserName"].ToString(),
                                userRole = sdr["UserRole"].ToString(),
                                userPhone = sdr["UserPhone"].ToString(),
                                userEmail = sdr["UserEmail"].ToString(),
                                userAddress = sdr["UserAddress"].ToString(),
                                userCity = sdr["UserCity"].ToString(),
                                isActive = sdr["IsActive"].ToString() == "True" ? "Active" : "Inactive"
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(userListClass);
        }

        public ActionResult AddItem()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddItemClass addItemClass = new AddItemClass();
            addItemClass.categories = new List<CategoryClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string queryGetCategory = "SELECT CategoryCode, CategoryName " +
                                          "FROM m_category ";
                using (MySqlCommand cmd = new MySqlCommand(queryGetCategory))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            addItemClass.categories.Add(new CategoryClass
                            {
                                categoryCode = sdr["CategoryCode"].ToString(),
                                categoryName = sdr["CategoryName"].ToString(),
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(addItemClass);
        }

        public ActionResult AddCategory()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddCategoryClass addCategoryClass = new AddCategoryClass();
            return View(addCategoryClass);
        }

        public ActionResult AddCustomer()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddCustomerClass addCustomerClass = new AddCustomerClass();
            return View(addCustomerClass);
        }

        public ActionResult AddUser()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddUserClass addUserClass = new AddUserClass();
            return View(addUserClass);
        }

        public ActionResult DetailsItem(string itemCode)
        {
            if (Session["userId"] == null)

SalesOrder/Views/MasterData/AddCategory.cshtml
@model SalesOrder.Models.MasterData.AddCategoryClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; ;
}

<link href="~/Assets/Nifty/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<style>
    .childCenter {
        margin: 0 auto;
        width: 100%;
        height: 100%;
        padding: 10px;
    }
</style>
<script src="~/Assets/EliteAdmin/node_modules/jquery/jquery-3.2.1.min.js"></script>

<script>
    $(document).ready(function () {
        $('#btnCancel').click(function () {
            window.location.href = "@Url.Action("CategoryList","MasterData")";
        });
    })
</script>

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Master Data</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Category</li>
                </ol>
                <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card ">
                <div class="card-header bg-info">
                    <h4 class="m-b-0 text-white">Add Category</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("SubmitCategory", "MasterData", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                        <div class="form-body">
                            <h3 class="box-title">Category Info</h3>
                            <hr class="m-t-0 m-b-40">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Code</label>
                                        <div class="col-md-9">
                                            @Html.TextBoxFor(model => model.categoryCode, new { @type = "text", @class = "form-control", @id = "txtCategoryCode" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="control-label text-right col-md-3">Name</label>
                                        <div class="col-md-9">
                                            @Html.TextBoxFor(model => model.categoryName, new { @type = "text", @class = "form-control", @id = "txtCategoryName" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-offset-3 col-md-9">
                                            <button type="submit" class="btn btn-success" id="btnSubmit">Submit</button>
                                            <button type="button" class="btn btn-inverse" id="btnCancel">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6"> </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SalesOrder/Views/MasterData/AddCustomer.cshtml
@model SalesOrder.Models.MasterData.AddCustomerClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; ;
}

<link href="~/Assets/Nifty/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<style>
    .childCenter {
        margin: 0 auto;
        width: 100%;
        height: 100%;
        padding: 10px;
    }
</style>
<script src="~/Assets/EliteAdmin/node_modules/jquery/jquery-3.2.1.min.js"></script>

<script>
    $(document).ready(function () {
        $('#btnCancel').click(function () {
            window.location.href = "@Url.Action("CustomerList","MasterData")";
        });
    })
</script>

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Master Data</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Customer</li>
                </ol>
                <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card ">
                <div class="card-header bg-info">
                    <h4 class="m-b-0 text-white">Add Customer</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("SubmitCustomer", "MasterData", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                    <div class="form-body">
                        <h3 class="box-title">Customer Info</h3>
                        <hr class="m-t-0 m-b-40">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Name</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.customerName, new { @type = "text", @class = "form-control", @id = "txtCustomerName" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Contact Person</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.contactPerson, new { @type = "text", @class = "form-control", @id = "txtContactPerson" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Phone</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.customerPhone, new { @type = "text", @class = "form-control", @id = "txtCustomerPhone" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Email</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.customerEmail, new { @type = "text", @class = "form-control", @id = "txtCustomerEmail" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">City</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.customerCity, new { @type = "text", @class = "form-control", @id = "txtCustomerCity" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Credit Limit</label>
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(model => model.creditLimit, new { @type = "number", @class = "form-control", @id = "txtCreditLimit" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                        <hr>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row">
                                        <div class="col-md-offset-3 col-md-9">
                                            <button type="submit" class="btn btn-success" id="btnSubmit">Submit</button>
                                            <button type="button" class="btn btn-inverse" id="btnCancel">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6"> </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SalesOrder/Views/MasterData/CategoryList.cshtml
@model SalesOrder.Models.MasterData.CategoryListClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; ;
}
<script src="~/Assets/EliteAdmin/node_modules/jquery/jquery-3.2.1.min.js"></script>
<script>
    var dtCategory;
    $(document).ready(function () {
        dtCategory = $('#dtCategory').DataTable();
    });
</script>

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Master Data</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Category</li>
                </ol>
                <a href="~/MasterData/AddCategory" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Category</h4>
                    <h6 class="card-subtitle">List</h6>
                    <div class="table-responsive m-t-40">
                        <table id="dtCategory" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Total Item</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.categories)
                                {
                                    <tr>
                                        <td style="text-align:center">@item.categoryCode</td>
                                        <td style="text-align:left">@item.categoryName</td>
                                        <td style="text-align:center">@item.totalItem</td>
                                        <td style="text-align:center">@item.isActive</td>
                                        <td style="text-align:center">
                                            <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/MasterData/DetailsCategory?categoryCode=@item.categoryCode" data-original-title="View" data-container="body"><i class="fa fa-edit"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>