SalesOrder/Models/Report/SODetailClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesOrder.Models.Report
{
    public class SODetailClass
    {
        public string statusCode { get; set; }
        public List<GetStatusClass> statues { get; set; }
    }

    public class GetReportSalesOrderDetail
    {
        public string SOCode { get; set; }
        public string postingDate { get; set; }
        public string documentDate { get; set; }
        public string deliveryDate { get; set; }
        public string customerCode { get; set; }
        public string customerName { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public int itemQty { get; set; }
        public double itemPrice { get; set; }
        public string strItemPrice { get; set; }
    }

    public class GetStatusClass
    {
        public string statusCode { get; set; }
        public string statusName { get; set; }
    }
}

SalesOrder/Controllers/ReportController.cs
using MySql.Data.MySqlClient;
using SalesOrder.Models.Report;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesOrder.Controllers
{
    public class ReportController : Controller
    {
        string constr = ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;

        public ActionResult SalesOrderDetail()
        {
            if (Session["userId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            SODetailClass sODetailClass = new SODetailClass();
            sODetailClass.statues = new List<GetStatusClass>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.StringId, a.StringName " +
                                "FROM m_stringmap a ";
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            sODetailClass.statues.Add(new GetStatusClass
                            {
                                statusCode = sdr["StringId"].ToString(),
                                statusName = sdr["StringName"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return View(sODetailClass);
        }

        public JsonResult GetSalesOrderDetail(string from, string to, string status)
        {
            long userId = long.Parse(Session["userId"].ToString());
            from = DateTime.ParseExact(from, "dd-MM-yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            to = DateTime.ParseExact(to, "dd-MM-yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            List<GetReportSalesOrderDetail> getReportSalesOrderDetails = new List<GetReportSalesOrderDetail>();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT a.SOCode, a.PostingDate, a.DocumentDate, a.DeliveryDate, a.CustomerCode, a.CustomerName, a.Notes, a.Status" +
                                ", b.ItemCode, b.ItemName, b.ItemQty, b.ItemPrice, c.StringName " +
                                "FROM t_salesorder a " +
                                "JOIN t_salesorderdetail b ON b.SOCode = a.SOCode " +
                                "JOIN m_stringmap c ON c.StringId = a.Status " + 
                                "WHERE a.CreatedBy = " + userId + " AND a.PostingDate BETWEEN '" + from + "' AND '" + to + "'";
                if (status != "-1")
                {
                    query = "SELECT a.SOCode, a.PostingDate, a.DocumentDate, a.DeliveryDate, a.CustomerCode, a.CustomerName, a.Notes, a.Status" +
                                ", b.ItemCode, b.ItemName, b.ItemQty, b.ItemPrice, c.StringName " +
                                "FROM t_salesorder a " +
                                "JOIN t_salesorderdetail b ON b.SOCode = a.SOCode " +
                                "JOIN m_stringmap c ON c.StringId = a.Status " +
                                "WHERE a.CreatedBy = " + userId + " AND a.Status = " + status + " AND a.PostingDate BETWEEN '" + from + "' AND '" + to + "'";
                }
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            getReportSalesOrderDetails.Add(new GetReportSalesOrderDetail
                            {
                                SOCode = sdr["SOCode"].ToString(),
                                postingDate = ((DateTime)sdr["PostingDate"]).ToString("dd-MM-yyyy"),
                                documentDate = ((DateTime)sdr["DocumentDate"]).ToString("dd-MM-yyyy"),
                                deliveryDate = ((DateTime)sdr["DeliveryDate"]).ToString("dd-MM-yyyy"),
                                customerCode = sdr["CustomerCode"].ToString(),
                                customerName = sdr["CustomerName"].ToString(),
                                notes = sdr["Notes"].ToString(),
                                status = sdr["StringName"].ToString(),
                                itemCode = sdr["ItemCode"].ToString(),
                                itemName = sdr["ItemName"].ToString(),
                                itemQty = Convert.ToInt32(sdr["ItemQty"].ToString()),
                                itemPrice = Convert.ToDouble(sdr["ItemPrice"].ToString()),
                                strItemPrice = Convert.ToDecimal(Convert.ToDouble(sdr["ItemPrice"].ToString())).ToString("#,###")
                            });
                        }
                    }
                    con.Close();
                }
                return Json(getReportSalesOrderDetails, JsonRequestBehavior.AllowGet);
            }
        }

        public string ConvertDateTimeFormat(string input, string inputFormat, string outputFormat, IFormatProvider culture)
        {
            DateTime dateTime = DateTime.ParseExact(input, inputFormat, culture);
            return dateTime.ToString(outputFormat, culture);
        }
    }
}

SalesOrder/Views/Report/SalesOrderDetail.cshtml
@model SalesOrder.Models.Report.SODetailClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; ;
}
<script src="~/Assets/EliteAdmin/node_modules/jquery/jquery-3.2.1.min.js"></script>
<script>
    var dtSalesOrderDetail;
    $(document).ready(function () {
        var now = new Date();
        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);
        var today = (day) + "-" + (month) + "-" + now.getFullYear();
        $('#txtFromDate').val(today);
        $('#txtToDate').val(today);
        dtSalesOrderDetail = $('#dtSalesOrderDetail').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'print',
                {
                    extend: 'excel'
                },
                {
                    extend: 'csv'
                }
            ],
            "columnDefs": [
                { 'visible': false, 'targets': [2, 3, 4, 6, 11] }
            ]
        });
        $('#btnGenerate').click(function () {
            var getFromDate = document.getElementById("txtFromDate").value;
            var getToDate = document.getElementById("txtToDate").value;
            var getcbStatus = document.getElementById("cbStatus");
            var getStatusCode = getcbStatus.options[getcbStatus.selectedIndex].value;
            $.getJSON("@Url.Action("GetSalesOrderDetail", "Report")?from=" + getFromDate + "&to=" + getToDate + "&status=" + getStatusCode, function (data) {
                dtSalesOrderDetail.destroy();
                $('#dtSalesOrderDetail').empty();
                dtSalesOrderDetail = $('#dtSalesOrderDetail').DataTable({
                    data: data,
                    columns: [
                        { "data": "SOCode", "title" : "Code" },
                        { "data": "postingDate", "title": "Posting Date" },
                        { "data": "documentDate", "title": "Doc Date" },
                        { "data": "deliveryDate", "title": "Delivery Date" },
                        { "data": "customerCode", "title": "Customer Code" },
                        { "data": "customerName", "title": "Customer Name" },
                        { "data": "notes", "title": "Notes" },
                        { "data": "status", "title": "Status" },
                        { "data": "itemCode", "title" : "Item Code" },
                        { "data": "itemName", "title": "Item Name" },
                        { "data": "itemQty", "title": "Item Qty" },
                        { "data": "strItemPrice", "title": "Item Price" }
                    ],
                    dom: 'Bfrtip',
                    buttons: [
                        'copy', 'print',
                        {
                            extend: 'excel'
                        },
                        {
                            extend: 'csv'
                        }
                    ],
                    "columnDefs": [
                        { 'visible': false, 'targets': [2, 3, 4, 6, 11] }
                    ]
                });
            });
        });
        $('.buttons-csv, .buttons-print, .buttons-excel').addClass('btn btn-primary mr-1');
        $('#txtFromDate').bootstrapMaterialDatePicker({ weekStart: 0, time: false, format: 'DD-MM-YYYY' });
        $('#txtToDate').bootstrapMaterialDatePicker({ weekStart: 0, time: false, format: 'DD-MM-YYYY' });
    });
    function checkdatetime() {
        var value1 = document.getElementById("txtFromDate").value;
        var value2 = document.getElementById("txtToDate").value;
        var strdt1 = value1.split("-");
        var finaldt1 = strdt1[2] + strdt1[1] + strdt1[0];
        var strdt2 = value2.split("-");
        var finaldt2 = strdt2[2] + strdt2[1] + strdt2[0];
        if (parseInt(finaldt1) > parseInt(finaldt2)) {
            $('#txtFromDate').val("");
            $('#txtToDate').val("");
        }
    }
</script>

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Report Sales Order per Item</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Sales Order Detail</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-body">
                        <h3 class="box-title">Sales Order per Item</h3>
                        <hr class="m-t-0 m-b-40">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">From Date</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" id="txtFromDate" onchange="checkdatetime()">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">To Date</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" id="txtToDate" onchange="checkdatetime()">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <label class="control-label text-right col-md-3">Status</label>
                                    <div class="col-md-9">
                                        @{
                                            List<SelectListItem> listStatus = new List<SelectListItem>();
                                            listStatus.Add(new SelectListItem
                                            {
                                                Text = "ALL",
                                                Value = "-1"
                                            });
                                            foreach (var item in Model.statues)
                                            {
                                                listStatus.Add(new SelectListItem
                                                {
                                                    Text = item.statusName,
                                                    Value = item.statusCode
                                                });
                                            }
                                        }
                                        @Html.DropDownListFor(model => model.statusCode, listStatus, new { @class = "form-control", @id = "cbStatus", @required = "required" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button id="btnGenerate" class="btn btn-success" type="button">Generate</button>
                    </div>
                    <div class="table-responsive m-t-40">
                        <table id="dtSalesOrderDetail" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="text-align:center">Code</th>
                                    <th style="text-align:center">Posting Date</th>
                                    <th style="text-align:center">Doc Date</th>
                                    <th style="text-align:center">Delivery Date</th>
                                    <th style="text-align:center">Customer Code</th>
                                    <th style="text-align:center">Customer Name</th>
                                    <th style="text-align:center">Notes</th>
                                    <th style="text-align:center">Status</th>
                                    <th style="text-align:center">Item Code</th>
                                    <th style="text-align:center">Item Name</th>
                                    <th style="text-align:center">Item Qty</th>
                                    <th style="text-align:center">Item Price</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>